apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deploy
  labels:
    service: elasticsearch-deploy

spec:
  replicas: 2
  selector:
    matchLabels:

  template:
    metadata:
      name: elasticsearch-pod
      labels:
        app: elasticsearch
        type: pod
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
          ports:
            - containerPort: 9200
            - containerPort: 9300

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    service: elasticsearch-deploy
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300


