apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    service: mongo-deploy
    type: bd

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongo
        type: pod
    spec:
      containers:
        - name: mongodb
          image: library/mongo:3
          ports:
            - containerPort: 27017



---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    service: mongo-deploy
  ports:
    - port: 27017
      name: "27017"
      targetPort: 27017
    - port:

