apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: elasticsearch
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  replicas: 3
  serviceName: elasticsearch-data
  selector:
    matchLabels:
      component: elasticsearch
      role: data
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      initContainers:
        - name: init-sysctl
          image: library/busybox:1.27.2
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: es-data
          image: quay.io/pires/docker-elasticsearch-kubernetes:6.2.4
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              value: my-es
            - name: NODE_MASTER
              value: "false"
            - name: NODE_INGEST
              value: "false"
            - name: HTTP_ENABLE
              value: "false"
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx256m
            - name: PROCESSORS
              value: "1"
              valueFrom:
                fieldRef:
                  fieldPath: limits.cpu
          resources:
            limits:
              cpu: 1
          ports:
            - containerPort: 9300
              name: transport
          volumeMounts:
            - mountPath: /data
              name: storage
  volumeClaimTemplates:
    - metadata:
        name: storage
        annotations:
          volume.beta.kubernetes.io/storage-class: "fast"
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "fast"
#        resources:
#          requests:
#            storage: 10Gi


















