apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  namespace: elasticsearch
  labels:
    component: elasticsearch
    role: data
spec:
  clusterIP: None
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    component: elasticsearch
    role: data